name: osc
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  universal_io: ^2.2.2
  typed_data: ^1.3.2
  udp: ^5.0.3
  dartudp:
    git:
      url: https://github.com/grogersstephen/dartudp.git
      ref: main
  logger: ^2.3.0
  path: ^1.9.1
  args: ^2.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
